version: '3.8'

services:
  api:
    image: mohamadayash22/real-inspire:latest
    container_name: real-inspire
    ports:
      - 3000:3000
    command: node server.js
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:1.25.4-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
